### PR TITLE
Fix incompatibility to new scijava LogService

### PR DESCRIPTION
**Pull request by maarzt**
Add implementations for the methods that were recently added to LogService.

A new version of scijva-log-slf4j containing this changes should be released together with scijava-common 2.66.2.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks @maarzt. I am releasing scijava-common 2.67.0 now (there was new API added, so a minor version bump was necessary). Please rebase this branch to eliminate the WIP:

* `git fetch && git rebase -i origin/master`.
* Move the WIP to the first commit in the list and change it to `e`.
* Save and quit to run the rebase.
* Update the POM to have `<scijava-common.version>2.67.0</scijava-common.version>` in the `<properties>` section. Commit it, changing the message accordingly. Note that you should not hardcode the `<version>` of any dependency, because then the melting-pot and similar tooling can no longer override the versions used on the CLI.
* `git rebase --continue`

It should then be the case that all commits compile with passing tests; the `check-branch.sh` script will verify this.

**Comment by maarzt** [comment]
Thanks for releasing the new scijava-common version. I did the rebase as you described.
 But not all commits compile:

* The first commit "POM: depend on scijava-common version 2.67.0" breaks the code. (SLF4JLogService has no implementations for new LogService methods like LogService::subLogger ...)

* The last commit "SLF4JLogService: support new LogService" fixes this.

Should I squash the two commits?

**Comment by ctrueden** [comment]
> Should I squash the two commits?

Sure, that's usually what we do when code changes need to happen concurrently with a dependency version update. So squashing the first two commits together, and keeping the second commit message, sounds great. Thanks.

One small typo in the message: `where` -> `were`.

**Comment by maarzt** [comment]
I think this branch is ready to be merged

**Comment by ctrueden** [comment]
Thanks @maarzt!

**Pull request merged**
